# Generated by Django 4.2.3 on 2023-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateField(),
        ),
    ]
