# Generated by Django 4.2.3 on 2023-08-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_post_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
    ]
