// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Books
export const GET_BOOK_LIST_SUCCESS = 'GET_BOOK_LIST_SUCCESS';
export const GET_BOOK_LIST_FAIL = 'GET_BOOK_LIST_FAIL';
export const GET_BOOK_LIST_CATEGORIES_SUCCESS = 'GET_BOOK_LIST_CATEGORIES_SUCCESS';
export const GET_BOOK_LIST_CATEGORIES_FAIL = 'GET_BOOK_LIST_CATEGORIES_FAIL';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';

export const GET_BOOK_PAGINATION_RESULTS_SUCCESS = 'GET_BOOK_PAGINATION_RESULTS_SUCCESS';
export const GET_BOOK_PAGINATION_RESULTS_FAIL = 'GET_BOOK_PAGINATION_RESULTS_FAIL';

export const GET_SEARCH_BOOK_SUCCESS = 'GET_SEARCH_BOOK_SUCCESS';
export const GET_SEARCH_BOOK_FAIL = 'GET_SEARCH_BOOK_FAIL';