# Generated by Django 4.2.6 on 2023-11-09 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lend_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user", models.EmailField(max_length=255)),
                ("lend_date", models.DateField()),
                ("expire_date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.post"
                    ),
                ),
            ],
        ),
    ]
